server {
    listen 443 ssl http2;
    server_name cangkujia666.com www.cangkujia666.com;

    ssl_certificate /etc/nginx/ssl/cangkujia666.com.crt;
    ssl_certificate_key /etc/nginx/ssl/cangkujia666.com.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    # 日志配置
    access_log /var/log/nginx/cangkujia-access.log;
    error_log /var/log/nginx/cangkujia-error.log;

    # 前端静态文件